return function()
    return {
        {
            {GRASS,GRASS  ,GRASS  ,GRASS  ,GRASS  ,GRASS  ,GRASS  ,GRASS  ,GRASS},
            {GRASS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,GRASS},
            {GRASS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,GRASS},
            {GRASS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,GRASS},
            {GRASS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,GRASS},
            {GRASS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,GRASS},
            {GRASS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,GRASS},
            {GRASS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS,GRASS},
            {GRASS,GRASS  ,GRASS  ,GRASS  ,GRASS  ,GRASS  ,GRASS  ,GRASS  ,GRASS}
        },
        {
            {AIR,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR},
            {AIR,LOG   ,PLANKS,PLANKS,PLANKS,PLANKS,PLANKS,LOG   ,AIR},
            {AIR,PLANKS,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,PLANKS,AIR},
            {AIR,PLANKS,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,PLANKS,AIR},
            {AIR,PLANKS,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,PLANKS,AIR},
            {AIR,PLANKS,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,PLANKS,AIR},
            {AIR,PLANKS,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,PLANKS,AIR},
            {AIR,LOG   ,PLANKS,PLANKS,PLANKS,PLANKS,AIR   ,LOG   ,AIR},
            {AIR,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR}
        },
        {
            {AIR,AIR   ,AIR  ,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR},
            {AIR,LOG   ,GLASS,GLASS ,GLASS ,GLASS ,GLASS ,LOG   ,AIR},
            {AIR,GLASS ,AIR  ,AIR   ,AIR   ,AIR   ,AIR   ,GLASS ,AIR},
            {AIR,GLASS ,AIR  ,AIR   ,AIR   ,AIR   ,AIR   ,GLASS ,AIR},
            {AIR,GLASS ,AIR  ,AIR   ,AIR   ,AIR   ,AIR   ,GLASS ,AIR},
            {AIR,GLASS ,AIR  ,AIR   ,AIR   ,AIR   ,AIR   ,GLASS ,AIR},
            {AIR,GLASS ,AIR  ,AIR   ,AIR   ,AIR   ,AIR   ,GLASS ,AIR},
            {AIR,LOG   ,GLASS,GLASS ,GLASS ,PLANKS,AIR   ,LOG   ,AIR},
            {AIR,AIR   ,AIR  ,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR}
        },
        {
            {AIR,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR},
            {AIR,LOG   ,PLANKS,PLANKS,PLANKS,PLANKS,PLANKS,LOG   ,AIR},
            {AIR,PLANKS,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,PLANKS,AIR},
            {AIR,PLANKS,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,PLANKS,AIR},
            {AIR,PLANKS,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,PLANKS,AIR},
            {AIR,PLANKS,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,PLANKS,AIR},
            {AIR,PLANKS,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,PLANKS,AIR},
            {AIR,LOG   ,PLANKS,PLANKS,PLANKS,PLANKS,PLANKS,LOG   ,AIR},
            {AIR,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR}
        },
        {
            {BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS},
            {BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS},
            {BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS},
            {BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS},
            {BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS},
            {BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS},
            {BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS},
            {BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS},
            {BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS}
        },
        {
            {AIR,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR},
            {AIR,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,AIR},
            {AIR,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,AIR},
            {AIR,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,AIR},
            {AIR,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,AIR},
            {AIR,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,AIR},
            {AIR,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,AIR},
            {AIR,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,AIR},
            {AIR,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR}
        },
        {
            {AIR,AIR,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR,AIR},
            {AIR,AIR,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR,AIR},
            {AIR,AIR,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,AIR,AIR},
            {AIR,AIR,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,AIR,AIR},
            {AIR,AIR,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,AIR,AIR},
            {AIR,AIR,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,AIR,AIR},
            {AIR,AIR,BRICKS,BRICKS,BRICKS,BRICKS,BRICKS,AIR,AIR},
            {AIR,AIR,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR,AIR},
            {AIR,AIR,AIR   ,AIR   ,AIR   ,AIR   ,AIR   ,AIR,AIR}
        },
    }
end
