return function()
    return {
        {
            {STONE,STONE,STONE,STONE,STONE},
            {STONE,STONE,STONE,STONE,STONE},
            {STONE,STONE,STONE,STONE,STONE},
            {STONE,STONE,STONE,STONE,STONE},
            {STONE,STONE,STONE,STONE,STONE},
        },
        {
            {AIR  ,SBRICKS,SBRICKS,SBRICKS,AIR},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {AIR  ,SBRICKS,AIR  ,SBRICKS,AIR},
        },
        {
            {AIR  ,SBRICKS,SBRICKS,SBRICKS,AIR},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {AIR  ,SBRICKS,AIR  ,SBRICKS,AIR},
        },
        {
            {AIR  ,SBRICKS,SBRICKS,SBRICKS,AIR},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {AIR  ,SBRICKS,SBRICKS,SBRICKS,AIR},
        },
        {
            {AIR  ,SBRICKS,SBRICKS,SBRICKS,AIR},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {AIR  ,SBRICKS,SBRICKS,SBRICKS,AIR},
        },
        {
            {SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS},
            {SBRICKS,AIR  ,SBRICKS,SBRICKS,SBRICKS},
            {SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS},
            {SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS},
            {SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS},
        },
        {
            {AIR  ,SBRICKS,SBRICKS,SBRICKS,AIR},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {AIR  ,SBRICKS,SBRICKS,SBRICKS,AIR},
        },
        {
            {AIR  ,SBRICKS,GLASS,SBRICKS,AIR},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {GLASS,AIR  ,AIR  ,AIR  ,GLASS},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {AIR  ,SBRICKS,GLASS,SBRICKS,AIR},
        },
        {
            {AIR  ,SBRICKS,GLASS,SBRICKS,AIR},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {GLASS,AIR  ,AIR  ,AIR  ,GLASS},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {AIR  ,SBRICKS,GLASS,SBRICKS,AIR},
        },
        {
            {AIR  ,SBRICKS,SBRICKS,SBRICKS,AIR},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {AIR  ,SBRICKS,SBRICKS,SBRICKS,AIR},
        },
        {
            {SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS},
            {SBRICKS,AIR  ,SBRICKS,SBRICKS,SBRICKS},
            {SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS},
            {SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS},
            {SBRICKS,SBRICKS,SBRICKS,SBRICKS,SBRICKS},
        },
        {
            {AIR  ,SBRICKS,SBRICKS,SBRICKS,AIR},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {AIR  ,SBRICKS,SBRICKS,SBRICKS,AIR},
        },
        {
            {AIR  ,AIR  ,SBRICKS,AIR  ,AIR},
            {AIR  ,AIR  ,AIR  ,AIR  ,AIR},
            {SBRICKS,AIR  ,AIR  ,AIR  ,SBRICKS},
            {AIR  ,AIR  ,AIR  ,AIR  ,AIR},
            {AIR  ,AIR  ,SBRICKS,AIR  ,AIR},
        },
    }
end
